/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MockupsIndexRouteImport } from './routes/mockups/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as CharactersNewRouteImport } from './routes/characters/new'
import { Route as CharactersIdEditRouteImport } from './routes/characters/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsIndexRoute = MockupsIndexRouteImport.update({
  id: '/mockups/',
  path: '/mockups/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersNewRoute = CharactersNewRouteImport.update({
  id: '/characters/new',
  path: '/characters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdEditRoute = CharactersIdEditRouteImport.update({
  id: '/characters/$id/edit',
  path: '/characters/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters/new': typeof CharactersNewRoute
  '/characters/': typeof CharactersIndexRoute
  '/mockups/': typeof MockupsIndexRoute
  '/characters/$id/edit': typeof CharactersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters/new': typeof CharactersNewRoute
  '/characters': typeof CharactersIndexRoute
  '/mockups': typeof MockupsIndexRoute
  '/characters/$id/edit': typeof CharactersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters/new': typeof CharactersNewRoute
  '/characters/': typeof CharactersIndexRoute
  '/mockups/': typeof MockupsIndexRoute
  '/characters/$id/edit': typeof CharactersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters/new'
    | '/characters/'
    | '/mockups/'
    | '/characters/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters/new'
    | '/characters'
    | '/mockups'
    | '/characters/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/characters/new'
    | '/characters/'
    | '/mockups/'
    | '/characters/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersNewRoute: typeof CharactersNewRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  MockupsIndexRoute: typeof MockupsIndexRoute
  CharactersIdEditRoute: typeof CharactersIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/': {
      id: '/mockups/'
      path: '/mockups'
      fullPath: '/mockups/'
      preLoaderRoute: typeof MockupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/new': {
      id: '/characters/new'
      path: '/characters/new'
      fullPath: '/characters/new'
      preLoaderRoute: typeof CharactersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id/edit': {
      id: '/characters/$id/edit'
      path: '/characters/$id/edit'
      fullPath: '/characters/$id/edit'
      preLoaderRoute: typeof CharactersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersNewRoute: CharactersNewRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  MockupsIndexRoute: MockupsIndexRoute,
  CharactersIdEditRoute: CharactersIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
