/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelationsIndexRouteImport } from './routes/relations/index'
import { Route as PlotsIndexRouteImport } from './routes/plots/index'
import { Route as MockupsIndexRouteImport } from './routes/mockups/index'
import { Route as DictionaryIndexRouteImport } from './routes/dictionary/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as PlotsNewRouteImport } from './routes/plots/new'
import { Route as PlotsIdRouteImport } from './routes/plots/$id'
import { Route as DictionaryIdRouteImport } from './routes/dictionary/$id'
import { Route as CharactersNewRouteImport } from './routes/characters/new'
import { Route as PlotsIdEditRouteImport } from './routes/plots/$id.edit'
import { Route as PlotsIdChapterPlanRouteImport } from './routes/plots/$id.chapter-plan'
import { Route as CharactersIdEditRouteImport } from './routes/characters/$id.edit'
import { Route as PlotsIdChaptersChapterIdRouteImport } from './routes/plots/$id.chapters.$chapterId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsIndexRoute = RelationsIndexRouteImport.update({
  id: '/relations/',
  path: '/relations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsIndexRoute = PlotsIndexRouteImport.update({
  id: '/plots/',
  path: '/plots/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsIndexRoute = MockupsIndexRouteImport.update({
  id: '/mockups/',
  path: '/mockups/',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryIndexRoute = DictionaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DictionaryRoute,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsNewRoute = PlotsNewRouteImport.update({
  id: '/plots/new',
  path: '/plots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsIdRoute = PlotsIdRouteImport.update({
  id: '/plots/$id',
  path: '/plots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryIdRoute = DictionaryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DictionaryRoute,
} as any)
const CharactersNewRoute = CharactersNewRouteImport.update({
  id: '/characters/new',
  path: '/characters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsIdEditRoute = PlotsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PlotsIdRoute,
} as any)
const PlotsIdChapterPlanRoute = PlotsIdChapterPlanRouteImport.update({
  id: '/chapter-plan',
  path: '/chapter-plan',
  getParentRoute: () => PlotsIdRoute,
} as any)
const CharactersIdEditRoute = CharactersIdEditRouteImport.update({
  id: '/characters/$id/edit',
  path: '/characters/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsIdChaptersChapterIdRoute =
  PlotsIdChaptersChapterIdRouteImport.update({
    id: '/chapters/$chapterId',
    path: '/chapters/$chapterId',
    getParentRoute: () => PlotsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/characters/new': typeof CharactersNewRoute
  '/dictionary/$id': typeof DictionaryIdRoute
  '/plots/$id': typeof PlotsIdRouteWithChildren
  '/plots/new': typeof PlotsNewRoute
  '/characters/': typeof CharactersIndexRoute
  '/dictionary/': typeof DictionaryIndexRoute
  '/mockups/': typeof MockupsIndexRoute
  '/plots/': typeof PlotsIndexRoute
  '/relations/': typeof RelationsIndexRoute
  '/characters/$id/edit': typeof CharactersIdEditRoute
  '/plots/$id/chapter-plan': typeof PlotsIdChapterPlanRoute
  '/plots/$id/edit': typeof PlotsIdEditRoute
  '/plots/$id/chapters/$chapterId': typeof PlotsIdChaptersChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/characters/new': typeof CharactersNewRoute
  '/dictionary/$id': typeof DictionaryIdRoute
  '/plots/$id': typeof PlotsIdRouteWithChildren
  '/plots/new': typeof PlotsNewRoute
  '/characters': typeof CharactersIndexRoute
  '/dictionary': typeof DictionaryIndexRoute
  '/mockups': typeof MockupsIndexRoute
  '/plots': typeof PlotsIndexRoute
  '/relations': typeof RelationsIndexRoute
  '/characters/$id/edit': typeof CharactersIdEditRoute
  '/plots/$id/chapter-plan': typeof PlotsIdChapterPlanRoute
  '/plots/$id/edit': typeof PlotsIdEditRoute
  '/plots/$id/chapters/$chapterId': typeof PlotsIdChaptersChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/characters/new': typeof CharactersNewRoute
  '/dictionary/$id': typeof DictionaryIdRoute
  '/plots/$id': typeof PlotsIdRouteWithChildren
  '/plots/new': typeof PlotsNewRoute
  '/characters/': typeof CharactersIndexRoute
  '/dictionary/': typeof DictionaryIndexRoute
  '/mockups/': typeof MockupsIndexRoute
  '/plots/': typeof PlotsIndexRoute
  '/relations/': typeof RelationsIndexRoute
  '/characters/$id/edit': typeof CharactersIdEditRoute
  '/plots/$id/chapter-plan': typeof PlotsIdChapterPlanRoute
  '/plots/$id/edit': typeof PlotsIdEditRoute
  '/plots/$id/chapters/$chapterId': typeof PlotsIdChaptersChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dictionary'
    | '/settings'
    | '/characters/new'
    | '/dictionary/$id'
    | '/plots/$id'
    | '/plots/new'
    | '/characters/'
    | '/dictionary/'
    | '/mockups/'
    | '/plots/'
    | '/relations/'
    | '/characters/$id/edit'
    | '/plots/$id/chapter-plan'
    | '/plots/$id/edit'
    | '/plots/$id/chapters/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/characters/new'
    | '/dictionary/$id'
    | '/plots/$id'
    | '/plots/new'
    | '/characters'
    | '/dictionary'
    | '/mockups'
    | '/plots'
    | '/relations'
    | '/characters/$id/edit'
    | '/plots/$id/chapter-plan'
    | '/plots/$id/edit'
    | '/plots/$id/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/dictionary'
    | '/settings'
    | '/characters/new'
    | '/dictionary/$id'
    | '/plots/$id'
    | '/plots/new'
    | '/characters/'
    | '/dictionary/'
    | '/mockups/'
    | '/plots/'
    | '/relations/'
    | '/characters/$id/edit'
    | '/plots/$id/chapter-plan'
    | '/plots/$id/edit'
    | '/plots/$id/chapters/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DictionaryRoute: typeof DictionaryRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  CharactersNewRoute: typeof CharactersNewRoute
  PlotsIdRoute: typeof PlotsIdRouteWithChildren
  PlotsNewRoute: typeof PlotsNewRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  MockupsIndexRoute: typeof MockupsIndexRoute
  PlotsIndexRoute: typeof PlotsIndexRoute
  RelationsIndexRoute: typeof RelationsIndexRoute
  CharactersIdEditRoute: typeof CharactersIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/': {
      id: '/relations/'
      path: '/relations'
      fullPath: '/relations/'
      preLoaderRoute: typeof RelationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/': {
      id: '/plots/'
      path: '/plots'
      fullPath: '/plots/'
      preLoaderRoute: typeof PlotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/': {
      id: '/mockups/'
      path: '/mockups'
      fullPath: '/mockups/'
      preLoaderRoute: typeof MockupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary/': {
      id: '/dictionary/'
      path: '/'
      fullPath: '/dictionary/'
      preLoaderRoute: typeof DictionaryIndexRouteImport
      parentRoute: typeof DictionaryRoute
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/new': {
      id: '/plots/new'
      path: '/plots/new'
      fullPath: '/plots/new'
      preLoaderRoute: typeof PlotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/$id': {
      id: '/plots/$id'
      path: '/plots/$id'
      fullPath: '/plots/$id'
      preLoaderRoute: typeof PlotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary/$id': {
      id: '/dictionary/$id'
      path: '/$id'
      fullPath: '/dictionary/$id'
      preLoaderRoute: typeof DictionaryIdRouteImport
      parentRoute: typeof DictionaryRoute
    }
    '/characters/new': {
      id: '/characters/new'
      path: '/characters/new'
      fullPath: '/characters/new'
      preLoaderRoute: typeof CharactersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/$id/edit': {
      id: '/plots/$id/edit'
      path: '/edit'
      fullPath: '/plots/$id/edit'
      preLoaderRoute: typeof PlotsIdEditRouteImport
      parentRoute: typeof PlotsIdRoute
    }
    '/plots/$id/chapter-plan': {
      id: '/plots/$id/chapter-plan'
      path: '/chapter-plan'
      fullPath: '/plots/$id/chapter-plan'
      preLoaderRoute: typeof PlotsIdChapterPlanRouteImport
      parentRoute: typeof PlotsIdRoute
    }
    '/characters/$id/edit': {
      id: '/characters/$id/edit'
      path: '/characters/$id/edit'
      fullPath: '/characters/$id/edit'
      preLoaderRoute: typeof CharactersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/$id/chapters/$chapterId': {
      id: '/plots/$id/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/plots/$id/chapters/$chapterId'
      preLoaderRoute: typeof PlotsIdChaptersChapterIdRouteImport
      parentRoute: typeof PlotsIdRoute
    }
  }
}

interface DictionaryRouteChildren {
  DictionaryIdRoute: typeof DictionaryIdRoute
  DictionaryIndexRoute: typeof DictionaryIndexRoute
}

const DictionaryRouteChildren: DictionaryRouteChildren = {
  DictionaryIdRoute: DictionaryIdRoute,
  DictionaryIndexRoute: DictionaryIndexRoute,
}

const DictionaryRouteWithChildren = DictionaryRoute._addFileChildren(
  DictionaryRouteChildren,
)

interface PlotsIdRouteChildren {
  PlotsIdChapterPlanRoute: typeof PlotsIdChapterPlanRoute
  PlotsIdEditRoute: typeof PlotsIdEditRoute
  PlotsIdChaptersChapterIdRoute: typeof PlotsIdChaptersChapterIdRoute
}

const PlotsIdRouteChildren: PlotsIdRouteChildren = {
  PlotsIdChapterPlanRoute: PlotsIdChapterPlanRoute,
  PlotsIdEditRoute: PlotsIdEditRoute,
  PlotsIdChaptersChapterIdRoute: PlotsIdChaptersChapterIdRoute,
}

const PlotsIdRouteWithChildren =
  PlotsIdRoute._addFileChildren(PlotsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DictionaryRoute: DictionaryRouteWithChildren,
  SettingsRoute: SettingsRoute,
  CharactersNewRoute: CharactersNewRoute,
  PlotsIdRoute: PlotsIdRouteWithChildren,
  PlotsNewRoute: PlotsNewRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  MockupsIndexRoute: MockupsIndexRoute,
  PlotsIndexRoute: PlotsIndexRoute,
  RelationsIndexRoute: RelationsIndexRoute,
  CharactersIdEditRoute: CharactersIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
